### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by demon101** [mhumeSF/terraform-provider-namedotcom#2]
I have tried with simple configuration, it works before, 
but on real config, it fails 

Can it be a problem of the wrong token? But in same time I see fresh Last Used date in name.com api page

```
Error: rpc error: code = Unavailable desc = transport is closing

2019/10/22 15:54:18 [TRACE] GRPCProvider: ApplyResourceChange
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: panic: runtime error: invalid memory address or nil pointer dereference
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd44f8f]
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: goroutine 15 [running]:
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/mhumesf/terraform-provider-namedotcom/namedotcom.resourceRecordRead(0xc4201491f0, 0xfaa760, 0xc42035aec0, 0x10edea0, 0xc420780160)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/mhumesf/terraform-provider-namedotcom/namedotcom/resource_namedotcom_record.go:67 +0xbf
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/mhumesf/terraform-provider-namedotcom/namedotcom.resourceRecordCreate(0xc4201491f0, 0xfaa760, 0xc42035aec0, 0x2, 0x16d7760)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/mhumesf/terraform-provider-namedotcom/namedotcom/resource_namedotcom_record.go:55 +0x280
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4204cc080, 0xc42008e3c0, 0xc4205f1e60, 0xfaa760, 0xc42035aec0, 0xc420298101, 0xc42033dd40, 0x16ab430)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:305 +0x36c
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4204cc180, 0xc420337960, 0xc42008e3c0, 0xc4205f1e60, 0xc42008caa8, 0xc4200d4ae0, 0xe5de00)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:289 +0xa4
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc4204d2008, 0x10f9c80, 0xc42033d4d0, 0xc420363e00, 0xc4204d2008, 0xc42033d440, 0xe685e0)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:885 +0x864
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xf7b820, 0xc4204d2008, 0x10f9c80, 0xc42033d4d0, 0xc42008e1e0, 0x0, 0x0, 0x0, 0xc42057c000, 0xde)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3189 +0x241
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4204e8900, 0x10ffdc0, 0xc4200a7c80, 0xc4202ff100, 0xc4203dfec0, 0x16ab860, 0x0, 0x0, 0x0)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:998 +0x4bc
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4204e8900, 0x10ffdc0, 0xc4200a7c80, 0xc4202ff100, 0x0)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:1278 +0xe02
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4204ca110, 0xc4204e8900, 0x10ffdc0, 0xc4200a7c80, 0xc4202ff100)
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:717 +0x9f
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: created by github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-10-22T15:54:20.052+0200 [DEBUG] plugin.terraform-provider-namedotcom: 	/home/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:715 +0xa1
2019-10-22T15:54:20.053+0200 [DEBUG] plugin: plugin process exited: path=/home/.terraform.d/plugins/terraform-provider-namedotcom pid=26243 error="exit status 2"
```

```
provider "namedotcom" {
  token = "XXXXXXXXXXXXXXXXXXXXXXXX"
  username = "XXXX"
}

resource "namedotcom_record" "rumix-com" {
  domain_name = "rumix.com"
  record_type = "A"
  host = "res"
  answer = "138.201.XX.XX"
}
```

```
Terraform v0.12.12
+ provider.namedotcom (unversioned)
```

**Comment by demon101** [comment]
the bug was caused by security settings in name.com and api returned the error:
```
{"message":"Permission Denied","details":"Authentication Error - Account Has Namesafe Enabled"}
```
